title: The Neverwoods, LLC
email: team@theneverwoods.com
description: "Hello. We are The Neverwoods. We design & build Apps, Websites, & Brands."
baseurl: ""
url: "http://theneverwoods.com" 
twitter_username: theneverwoods
github_username:  theneverwoods
sass:
    style: compressed
gems:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
